title: Amadeus Vadonis - Evangelisation
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

defaults:
  -
    scope:
      path: "_posts" # empty string for all files
    values:
      excerpt_separator: "<!--mehr-->"


# Build settings
markdown: kramdown
theme: custom-theme
plugins:
  - jekyll-feed

# Jekyll Assets
assets:
  sources:
    - _custom-theme/assets
  autoprefixer:
    browsers:
    - "last 3 versions"
    - "IE > 9"
  plugins:
    img:
      # optim: false # To deactivate automatic optimization
      optim:
        {}

# Exclude from processing.
exclude:
  # Default:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # Custom:
  - .gitignore
  - .jekyll-metadata
