titel: Amadeus Vadonis - Evangelisation
titel_englisch: Amadeus Vadonis - Evangelisation
beschreibung: Beschreibung der Webseite
beschreibung_englisch: Description of the website
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
timezone: "Europe/Berlin" # important for dates

defaults:
  -
    scope:
      path: "_posts" # empty string for all files
    values:
      excerpt_separator: "<!--mehr-->"
      style_id: post
      layout: post

collections:
  posts:
    permalink: /blog/:title/

# Build settings
markdown: kramdown
theme: custom-theme
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate

# Pagination
paginate: 6
paginate_path: "/blog/page:num/"

# Jekyll Assets
assets:
  sources:
    - _custom-theme/assets
  autoprefixer:
    browsers:
    - "last 3 versions"
    - "IE > 9"
  plugins:
    img:
      # optim: false # To deactivate automatic optimization
      optim:
        {}

# Exclude from processing.
exclude:
  # Default:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # Custom:
  - .gitignore
  - .jekyll-metadata
