---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: document
  path: index.html
  label: Hauptseite (deutsch)
- type: document
  path: en/index.html
  label: Hauptseite (englisch)
- type: document
  path: _data/termine.yml
  label: Gebuchte Termine
- type: jekyll-posts
  label: Blog Artikel
  create: documents
  templates:
  - blog-post
- type: heading
  label: Unterseiten
- type: document
  path: blog/index.html
  label: Blog Titelseite
- type: document
  path: datenschutz.md
  label: Datenschutz
- type: document
  path: impressum.md
  label: Impressum
- type: document
  path: 404.html
  label: 404 Fehlerseite
upload_dir: media/uploads
public_path: "/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
