---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: jekyll-posts
  label: Blog Artikel
  create: documents
- type: jekyll-pages
  label: Seiten
  create: none
upload_dir: media
public_path: "/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
