backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  # accept_roles: #optional - accepts all users if left out
  #   - admin
  #   - editor
# publish_mode: editorial_workflow
media_folder: "./media" # Media files will be stored in the repo under ./media
# public_folder: "/media" # The src attribute for uploaded media will begin with ./media
collections:
- name: "blog-artikel" # Used in routes, e.g., /admin/collections/blog
  label: "Blog Artikel" # Used in the UI
  folder: "_posts" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
    - {label: "Titel", name: "titel", widget: "string"}
    - {label: "Datum", name: "datum", widget: "datetime"}
    - {label: "Titelbild (optional)", name: "titel_bild", widget: "image"}
    - {label: "Body", name: "body", widget: "markdown"}
- label: "Seiten"
  name: "seiten"
  files:
    - label: "Hauptseite"
      name: "home"
      file: "_seiten/index.html"
      format: "yaml-frontmatter"
      extension: "html"
      fields:
        - {label: Titel, name: title, widget: string}
        - label: Predigten
          name: predigten
          widget: list
          fields:
            - {label: Titel, name: title, widget: string}
            - {label: Datum, name: date, widget: date, format: "DD.MM.YYYY"}
            - {label: Audiodatei, name: file, widget: file}
    - label: "Fehlerseite (404)"
      name: "404"
      file: "_seiten/404.html"
      fields:
        - {label: Erste Zeile, name: erste_zeile, widget: string}
        - {label: Zweite Zeile, name: zweite_zeile, widget: markdown}
    - label: "Impressum"
      name: "impressum"
      file: "_seiten/impressum.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: "Body", name: "body", widget: "markdown"}
