backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# publish_mode: editorial_workflow
media_folder: "media" # Media files will be stored in the repo under ./media
# public_folder: "/media" # The src attribute for uploaded media will begin with ./media
collections:
- label: "Seiten"
  name: "seiten"
  files:
    - label: "Hauptseite"
      name: "home"
      file: "index.html"
      fields:
        - {label: Titel, name: title, widget: string}
        - label: Predigten
          name: predigten
          widget: list
          fields:
            - {label: Titel, name: title, widget: string}
            - {label: Datum, name: date, widget: date, format: "DD.MM.YYYY"}
            - {label: Audiodatei, name: file, widget: file}
    # - label: "Locations Page"
    #   name: "locations"
    #   file: "site/content/locations.yml"
    #   fields:
    #     - {label: Title, name: title, widget: string}
    #     - {label: Intro, name: intro, widget: markdown}
    #     - label: Locations
    #       name: locations
    #       widget: list
    #       fields:
    #         - {label: Name, name: name, widget: string}
    #         - {label: Address, name: address, widget: string}
