backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  # accept_roles: #optional - accepts all users if left out
  #   - admin
  #   - editor
# publish_mode: editorial_workflow
media_folder: "media" # Media files will be stored in the repo under ./media
# public_folder: "/media" # The src attribute for uploaded media will begin with ./media
collections:
- label: "Seiten"
  name: "seiten"
  files:
    - label: "Impressum"
      name: "impressum"
      file: "impressum.md"
      fields:
        - {label: Title, name: title, widget: string}
        # - {label: Content, name: content, widget: markdown}
    # - label: "Locations Page"
    #   name: "locations"
    #   file: "site/content/locations.yml"
    #   fields:
    #     - {label: Title, name: title, widget: string}
    #     - {label: Intro, name: intro, widget: markdown}
    #     - label: Locations
    #       name: locations
    #       widget: list
    #       fields:
    #         - {label: Name, name: name, widget: string}
    #         - {label: Address, name: address, widget: string}
